default:
  image: python:3.12

stages:
  - linting
  - testing
  - building

flake8:
  stage: linting
  script:
    - pip install flake8
    - flake8 suggestio_backend

django-tests:
  stage: testing
  script:
    - pip install
    - poetry install
    - cd suggestio_backend
    - python manage.py test

build:
  stage: building
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_KEY
    
    - docker build -t $DOCKER_REGISTRY_USER/suggestio-nginx nginx/
    - docker push $DOCKER_REGISTRY_USER/suggestio-nginx

    - docker build -t $DOCKER_REGISTRY_USER/suggestio-web -f DOCKERFILE .
    - docker push $DOCKER_REGISTRY_USER/suggestio-web
