FROM python:3.12

ENV PYTHONUBUFFERED=1

RUN mkdir /home/app/
RUN mkdir /home/app/web/
RUN mkdir /home/app/web/static
WORKDIR /home/app/web

COPY suggestio_backend/static /home/app/static

RUN pip install --upgrade pip "poetry==1.8.4"

RUN poetry config virtualenvs.create false --local

COPY poetry.lock pyproject.toml ./

RUN poetry install

COPY suggestio_backend /home/app/web
