FROM python:3.12

ENV PYTHONUBUFFERED=1

WORKDIR /app

RUN pip install --upgrade pip "poetry==1.8.4"

RUN poetry config virtualenvs.create false --local

COPY poetry.lock pyproject.toml ./

RUN poetry install

COPY suggestio_backend .
