name: Manual Deployment
on: workflow_dispatch

env:
  BACKEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/suggestio:${{ github.sha }}
  NGINX_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/suggestio-nginx:${{ github.sha }}

jobs:
  build-backend:
    environment: env
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: yacloud-deploy

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./DOCKERFILE
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/suggestio:${{ github.sha }}

  build-nginx:
    environment: env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: yacloud-deploy

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Nginx for together composing
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/suggestio-nginx:${{ github.sha }}

  update-yc:
    runs-on: ubuntu-latest
    environment: env
    needs: [build-backend, build-nginx]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: yacloud-deploy
        
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Deploy COI VM
      id: deploy-coi
      uses: yc-actions/yc-coi-deploy@v1.0.1
      env:
        BACKEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/suggestio:${{ github.sha }}
        NGINX_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/suggestio-nginx:${{ github.sha }}
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        VM-name: ${{ secrets.YC_VM_NAME }}
        vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
        vm-cores: 2
        vm-platform-id: 'standard-v2'
        vm-memory: 512Mb
        vm-disk-size: 30Gb
        vm-core-fraction: 5
        docker-compose-path: './yacloud/docker-compose.yaml'
        user-data-path: './yacloud/user-data.yaml'
